### ISSUE TITLE
how to use with SSH.net

### ISSUE THREAD

**Issue by karqical2016** [samstk/WFTerminal#1]
how to use  WFTerminal with Renci.SshNet in winform by C#,could you have a example

**Comment by samstk** [comment]
Hi, Karqical2016, I'll have a look into this in the following days. I've once redirected a Putty-like / Shell stream to the terminal control (with limited support - some features broken - I may end up updating the package if needed). It may have something to do with creating a shell (and redirecting via GetInputStream and GetOutputStream on the terminal)

- If you just wish to write to the Console.WriteLine (like in Renci.SSHNET examples) and have it show up in the terminal, you can use RedirectStandardConsoleOut, or just write to the terminal directly (via WriteLine).
- Since the terminal works in an event/callback-based manner, you may have to keep this in mind for any Read inputs.

**Comment by samstk** [comment]
Hi, Karqical2016, I've had a look and have now updated the package to version 1.1.0. This version now has limited direct support for system / shell streams. I've provided an example as per [The Github Page](https://github.com/samstk/WFTerminal) for an example on how to connect. From testing, it tends to work well with basic commands, however:

Please note that some features won't work with the current level of support for ANSI (like text editors), and that while using a shell stream other features may be unavailable (although you could possibly switch between standard modes and shell modes).

More ANSI code support is planned in the future but it will be a little while as I'm working on the project very sparsely. 

Thanks.
